{ config, pkgs, ... }:
# AGS (Astal dashboard) — manages the TypeScript app and launcher script.
# style.css is intentionally EXCLUDED — generated by apply.sh from a template.
{
  home.file = {
    ".config/ags/app.ts".source = ../dotfiles/ags/app.ts;

    ".config/ags/launch.sh" = {
      source     = ../dotfiles/ags/launch.sh;
      executable = true;
    };

    # GSettings schemas required at runtime
    ".config/ags/schemas/io.astal.notifd.gschema.xml".source = ../dotfiles/ags/schemas/io.astal.notifd.gschema.xml;
    ".config/ags/schemas/gschemas.compiled".source            = ../dotfiles/ags/schemas/gschemas.compiled;
  };
}
