{ config, pkgs, ... }:
# Fastfetch — manages the compact config and logo assets.
# config.jsonc (main) is EXCLUDED — generated by apply.sh from a template.
{
  home.file = {
    ".config/fastfetch/config-compact.jsonc".source = ../dotfiles/fastfetch/config-compact.jsonc;
    ".config/fastfetch/arch.png".source             = ../dotfiles/fastfetch/arch.png;

    # Logo assets (read-only references)
    ".config/fastfetch/logo/archlinux_ascii.txt".source = ../dotfiles/fastfetch/logo/archlinux_ascii.txt;
    ".config/fastfetch/logo/archlinux.png".source       = ../dotfiles/fastfetch/logo/archlinux.png;
    ".config/fastfetch/logo/aisaka.icon".source         = ../dotfiles/fastfetch/logo/aisaka.icon;
    ".config/fastfetch/logo/hyprland.icon".source       = ../dotfiles/fastfetch/logo/hyprland.icon;
    ".config/fastfetch/logo/loli.icon".source           = ../dotfiles/fastfetch/logo/loli.icon;
    ".config/fastfetch/logo/pochita.icon".source        = ../dotfiles/fastfetch/logo/pochita.icon;
    ".config/fastfetch/logo/ryuzaki.icon".source        = ../dotfiles/fastfetch/logo/ryuzaki.icon;
  };
}
