{ config, pkgs, ... }:
# Kitty — manages the structural config.
# kitty-colors.conf is intentionally EXCLUDED — generated by apply.sh.
{
  home.file = {
    ".config/kitty/kitty.conf".source = ../dotfiles/kitty/kitty.conf;
  };
}
