{ config, pkgs, ... }:
# Rofi — manages the base config.rasi only.
# theme.rasi, theme-picker.rasi, and wallpaper-picker.rasi are EXCLUDED —
# they are all generated by apply.sh from templates and must remain writable.
{
  home.file = {
    ".config/rofi/config.rasi".source = ../dotfiles/rofi/config.rasi;
  };
}
