{ config, pkgs, ... }:
# SwayNC — manages the structural config.json (layout/widgets/position).
# style.css is intentionally EXCLUDED — generated by apply.sh from a template.
{
  home.file = {
    ".config/swaync/config.json".source = ../dotfiles/swaync/config.json;
  };
}
