/* ── {{THEME_NAME}} — AGS Style ──────────────────────────────────────────── */
/* Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead */

* {
    font-family: "FiraCode Nerd Font Mono", monospace;
    font-size: 13px;
    transition: 120ms ease;
    outline: none;
    box-shadow: none;
}

button {
    outline: none;
    box-shadow: none;
}

button:focus,
button:active,
button:checked {
    outline: none;
    box-shadow: none;
}

/* ── Dashboard window ─────────────────────────────────────────────────────── */

window.dashboard {
    background-color: transparent;
}

window.dashboard scrolledwindow,
window.dashboard scrolledwindow viewport {
    background-color: transparent;
}

.dashboard {
    background-color: rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.7);
    border-radius: 16px;
    border: 1px solid #{{ACCENT}};
    padding: 16px;
    box-shadow: 0 8px 32px rgba(0,0,0,0.6);
}

/* ── Panels ───────────────────────────────────────────────────────────────── */

.panel {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.8);
    border-radius: 12px;
    padding: 16px;
    border: 1px solid rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.25);
}

.notif-panel {
    min-width: 260px;
    min-height: 400px;
}

.right-panel {
    min-width: 230px;
}

/* ── Panel header ─────────────────────────────────────────────────────────── */

.panel-title {
    font-size: 11px;
    font-weight: bold;
    color: #{{ACCENT}};
    letter-spacing: 1px;
}

.clear-btn {
    font-size: 11px;
    color: #{{ACCENT_ALT}};
    padding: 2px 10px;
    border-radius: 6px;
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.8);
    border: 1px solid rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.25);
}

.clear-btn:hover {
    color: #{{FG}};
    background-color: rgba({{BG_HOVER_R}}, {{BG_HOVER_G}}, {{BG_HOVER_B}}, 0.9);
}

.clear-btn:active {
    background-color: rgba({{BG_ACTIVE_R}}, {{BG_ACTIVE_G}}, {{BG_ACTIVE_B}}, 0.9);
    color: #{{FG}};
}

/* ── Notification items (dashboard) ──────────────────────────────────────── */

.notification-item {
    background-color: rgba({{BG_BLUR_R}}, {{BG_BLUR_G}}, {{BG_BLUR_B}}, 0.5);
    border-radius: 10px;
    padding: 10px 12px;
    border: 1px solid rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.15);
    border-left: 3px solid #{{ACCENT}};
    margin-bottom: 6px;
}

.notification-item.critical {
    border-left-color: #{{URGENT}};
}

.notification-item.low {
    border-left-color: #{{ACCENT_ALT}};
}

.notif-summary {
    font-size: 12px;
    font-weight: bold;
    color: #{{FG}};
}

.notif-body {
    font-size: 11px;
    color: #{{FG_SUBTLE}};
    margin-top: 3px;
}

.notif-item-btn {
    background: transparent;
    border: none;
    padding: 0;
    border-radius: 6px;
}

.notif-item-btn:hover {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.08);
}

.notif-item-btn:active {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.15);
}

.notif-close-btn {
    color: #{{FG_MUTED}};
    font-size: 13px;
    padding: 0 4px;
    border-radius: 4px;
    min-width: 22px;
    border: none;
    background: transparent;
}

.notif-close-btn:hover {
    color: #{{URGENT}};
}

.notif-close-btn:active {
    color: #{{URGENT_DARK}};
}

.notif-empty {
    color: #{{FG_MUTED}};
    font-size: 12px;
    font-style: italic;
    padding: 24px 0;
}

/* ── Scrollable ───────────────────────────────────────────────────────────── */

scrolledwindow,
scrolledwindow > viewport,
scrolledwindow > viewport > box {
    background-color: transparent;
}

scrollbar {
    background-color: transparent;
    min-width: 4px;
}

scrollbar slider {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.2);
    border-radius: 4px;
    min-width: 4px;
    min-height: 24px;
}

scrollbar slider:hover {
    background-color: #{{ACCENT_ALT}};
}

/* ── Section labels ───────────────────────────────────────────────────────── */

.section-label {
    font-size: 10px;
    font-weight: bold;
    color: #{{FG_MUTED}};
    letter-spacing: 1.5px;
    margin-bottom: 6px;
}

/* ── Divider ──────────────────────────────────────────────────────────────── */

.divider {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.2);
    min-height: 1px;
    margin: 6px 0;
}

/* ── Media player ─────────────────────────────────────────────────────────── */

.track-title {
    font-size: 15px;
    font-weight: bold;
    color: #{{FG}};
    margin-top: 2px;
}

.track-artist {
    font-size: 12px;
    color: #{{FG_SUBTLE}};
    margin-top: 2px;
}

.media-controls {
    margin-top: 10px;
}

.media-btn {
    padding: 7px 16px;
    border-radius: 10px;
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.8);
    color: #{{FG}};
    font-size: 15px;
    border: 1px solid rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.2);
    min-width: 38px;
}

.media-btn:hover {
    background-color: rgba({{BG_HOVER_R}}, {{BG_HOVER_G}}, {{BG_HOVER_B}}, 0.9);
}

.media-btn:active {
    background-color: rgba({{BG_ACTIVE_R}}, {{BG_ACTIVE_G}}, {{BG_ACTIVE_B}}, 0.9);
}

.play-btn {
    background-color: #{{ACCENT}};
    color: #{{BG_BASE}};
    padding: 9px 22px;
    font-size: 17px;
    border: none;
}

.play-btn:hover {
    background-color: #{{ACCENT_LIGHT}};
}

.play-btn:active {
    background-color: #{{ACCENT_ALT}};
}

/* ── Calendar ─────────────────────────────────────────────────────────────── */

.calendar-body {
    font-family: "FiraCode Nerd Font Mono", monospace;
    font-size: 12px;
    color: #{{FG_SUBTLE}};
    letter-spacing: 0.5px;
}

/* ── Notification avatar (sender profile picture) ────────────────────────── */

.notif-avatar {
    border-radius: 50%;
    margin-right: 10px;
}

/* ── Notification popups ──────────────────────────────────────────────────── */

window.notifications-popup > box {
    background-color: transparent;
}

.notif-popup {
    background-color: rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.7);
    border: 1px solid #{{ACCENT}};
    border-left: 3px solid #{{ACCENT}};
    border-radius: 10px;
    padding: 12px 14px;
    min-width: 320px;
    box-shadow: 0 4px 16px rgba(0,0,0,0.5);
}

.notif-popup.critical {
    border-color: #{{URGENT}};
    border-left-color: #{{URGENT}};
}

.notif-popup.low {
    border-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.2);
    border-left-color: #{{ACCENT_ALT}};
}

.notif-popup-app {
    font-size: 10px;
    font-weight: bold;
    color: #{{FG_MUTED}};
    letter-spacing: 0.5px;
}

.notif-popup-summary {
    font-size: 13px;
    font-weight: bold;
    color: #{{FG}};
    margin-top: 3px;
}

.notif-popup-body {
    font-size: 12px;
    color: #{{FG_SUBTLE}};
    margin-top: 4px;
}

.notif-popup-body-btn {
    background: transparent;
    border: none;
    padding: 0;
    border-radius: 6px;
}

.notif-popup-body-btn:hover {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.08);
}

.notif-popup-body-btn:active {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.15);
}

.notif-popup-close {
    color: #{{FG_MUTED}};
    font-size: 13px;
    padding: 0 4px;
    border-radius: 4px;
    border: none;
    background: transparent;
}

.notif-popup-close:hover {
    color: #{{URGENT}};
}

.notif-popup-close:active {
    color: #{{URGENT_DARK}};
}
