-- Auto-generated by apply.sh from theme: {{THEME_NAME}}
-- Do not edit — run apply.sh <theme-name> to update

return {
    active_1 = "rgba({{BORDER1}})",
    active_2 = "rgba({{BORDER2}})",
    inactive = "rgba({{BORDER_INACTIVE}})",
}
