# Auto-generated by apply.sh from theme: {{THEME_NAME}}
# Do not edit — run ~/.config/themes/apply.sh <theme-name> to update.
#
# Nebula-style lock screen, themed to the active palette.
#   • Background = your CURRENT wallpaper, blurred. The path below is a stable
#     symlink (~/.cache/wallpaper-picker/current) that apply.sh and the
#     wallpaper picker keep pointed at whatever wallpaper is live, so the lock
#     screen always matches the desktop (Super+W or Super+Shift+W).
#   • All colors are pulled from the theme, so it re-tints on every theme swap.
#
# NOTE: hyprlock only authenticates the CURRENT session user. The TAB key is
# neutralised during lock by a bindl added in scripts/lock.sh (hyprlock has no
# key-ignore option of its own).
#
# REQUIREMENTS: a Nerd Font (icons) + Inter. e.g. "JetBrainsMono Nerd Font".

general {
    hide_cursor = true
    ignore_empty_input = true
}

# ───────────────────────── BACKGROUND ─────────────────────────
background {
    monitor =
    # Stable symlink → current wallpaper (kept fresh by apply.sh / wallpaper-mode.sh)
    path = ~/.cache/wallpaper-picker/current

    # Fallback / tint if the symlink target is missing: theme base background
    color = rgba({{BG_BASE}}ff)

    blur_passes = 3
    blur_size = 6
    noise = 0.012
    contrast = 0.95
    brightness = 0.80
    vibrancy = 0.20
    vibrancy_darkness = 0.10
}

# ───────────────────────── PASSWORD FIELD ─────────────────────────
input-field {
    monitor =
    size = 250, 50
    rounding = 26
    outline_thickness = 2

    # Accent glow border + translucent themed interior
    outer_color = rgba({{ACCENT}}8c)
    inner_color = rgba({{BG_SURFACE}}73)
    font_color  = rgb({{FG}})

    # Glow effect around the field
    shadow_passes = 3
    shadow_size = 7
    shadow_color = rgba({{ACCENT}}73)
    shadow_boost = 1.4

    dots_size = 0.22
    dots_spacing = 0.34
    dots_center = true
    dots_rounding = -1

    fade_on_empty = false
    placeholder_text =
    hide_input = false

    check_color = rgb({{INFO}})
    fail_color  = rgb({{URGENT}})
    fail_text   = <i>$FAIL</i>

    position = 0, 0
    halign = center
    valign = center
}

# ───────────────────────── USER ─────────────────────────
# Account-circle avatar stacked ABOVE the username (no overlap, any length).
# Comment kept off the text line so it never pollutes / clips the glyph.
label {
    monitor =
    # Nerd Font glyph: nf-md-account_circle
    text =  󰀉 
    color = rgb({{ACCENT}})
    font_size = 40
    font_family = FiraCode Nerd Font
    position = 0, 145
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[] whoami
    color = rgb({{FG}})
    font_size = 24
    font_family = Inter
    position = 0, 88
    halign = center
    valign = center
}

# ───────────────────────── USER DOT ─────────────────────────
# Single accent dot beneath the username (decorative).
label {
    monitor =
    text = ●
    color = rgb({{ACCENT}})
    font_size = 16
    font_family = FiraCode Nerd Font
    position = 0, -130
    halign = center
    valign = center
}
