# ── Colors — {{THEME_NAME}} ───────────────────────────────────────────────────
# Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead

background  #{{BG}}
foreground  #{{FG}}

cursor            #{{ACCENT}}
cursor_text_color #{{BG}}

selection_background #{{SELECTION}}
selection_foreground #{{FG}}

url_color #{{INFO}}

# ── 16 ANSI colors ───────────────────────────────────────────────────────────
# Black
color0  #{{BLACK_DIM}}
color8  #{{FG_MUTED}}

# Red (urgent/error)
color1  #{{URGENT}}
color9  #{{URGENT}}

# Green
color2  #{{GREEN}}
color10 #{{GREEN}}

# Yellow (warning)
color3  #{{WARNING}}
color11 #{{WARNING}}

# Blue (info)
color4  #{{INFO}}
color12 #{{INFO}}

# Magenta (accent)
color5  #{{ACCENT}}
color13 #{{ACCENT}}

# Cyan
color6  #{{CYAN_TERM}}
color14 #{{CYAN_TERM}}

# White
color7  #{{FG}}
color15 #{{FG}}

# ── Tab bar colors ────────────────────────────────────────────────────────────
tab_bar_background           #{{BG}}
active_tab_background        #{{BG_MEDIUM}}
active_tab_foreground        #{{ACCENT}}
inactive_tab_background      #{{BG}}
inactive_tab_foreground      #{{FG_MUTED}}
