# ── {{THEME_NAME}} — Mako Config ─────────────────────────────────────────────
# Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead
sort=+time
layer=overlay
anchor=top-right
margin=10
padding=10,15
border-size=1
border-radius=8
default-timeout=5000
ignore-timeout=0
max-visible=5

background-color=#{{BG}}
text-color=#{{FG}}
border-color=#{{ACCENT}}

[urgency=low]
background-color=#{{BG}}
border-color=#{{ACCENT_ALT}}

[urgency=normal]
background-color=#{{BG}}
border-color=#{{ACCENT}}

[urgency=critical]
background-color=#{{BG_HIGH}}
border-color=#{{URGENT}}
default-timeout=0
