/* ── {{THEME_NAME}} — Theme Picker ──────────────────────────────────────── */
/* Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead */

* {
    background-color:            transparent;
    text-color:                  #{{FG}};
    foreground:                  #{{FG}};
    background:                  rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.92);
    separatorcolor:              rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.30);
    border-color:                rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.40);
    spacing:                     0;
    normal-foreground:           @foreground;
    normal-background:           transparent;
    alternate-normal-foreground: @foreground;
    alternate-normal-background: transparent;
    selected-normal-foreground:  #{{ACCENT}};
    selected-normal-background:  rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.15);
}

window {
    font:             "FiraCode Nerd Font 13";
    background-color: rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.92);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.45);
    border-radius:    20px;
    width:            540px;
    padding:          14px;
    children:         [ inputbar, listview ];
    spacing:          12px;
}

inputbar {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.90);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.35);
    border-radius:    14px;
    padding:          10px 16px;
    children:         [ prompt, textbox-prompt-colon, entry ];
    spacing:          8px;
}

prompt {
    background-color: transparent;
    text-color:       #{{ACCENT}};
    font:             "FiraCode Nerd Font Bold 13";
    vertical-align:   0.5;
}

textbox-prompt-colon {
    background-color: transparent;
    text-color:       #{{ACCENT_ALT}};
    str:              "→";
    vertical-align:   0.5;
}

entry {
    background-color: transparent;
    text-color:       #{{FG}};
    placeholder:      "Switch theme…";
    placeholder-color: rgba({{FG_R}}, {{FG_G}}, {{FG_B}}, 0.35);
    vertical-align:   0.5;
}

listview {
    background-color: transparent;
    lines:            8;
    columns:          1;
    spacing:          6px;
    fixed-height:     false;
    scrollbar:        false;
    cycle:            true;
}

element {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.40);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.10);
    border-radius:    12px;
    padding:          10px 14px;
    spacing:          16px;
    orientation:      horizontal;
    cursor:           pointer;
}

element.selected {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.18);
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.70);
    border:           2px;
}

element-icon {
    background-color: transparent;
    size:             80px;
    border-radius:    8px;
    border:           0px;
}

element-text {
    background-color: transparent;
    text-color:       inherit;
    vertical-align:   0.5;
    font:             "FiraCode Nerd Font Bold 15";
}
