/* ── {{THEME_NAME}} — Wallpaper Picker ──────────────────────────────────── */
/* Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead */

configuration {
    kb-page-prev:    "Page_Up,ScrollUp";
    kb-page-next:    "Page_Down,ScrollDown";
    ml-row-up:       "";
    ml-row-down:     "";
    me-accept-entry: "MousePrimary";
    me-select-entry: "";
    hover-select:    true;
}

* {
    background-color:            transparent;
    text-color:                  #{{FG}};
    foreground:                  #{{FG}};
    background:                  rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.92);
    separatorcolor:              rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.30);
    border-color:                rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.35);
    spacing:                     0;
    normal-background:           transparent;
    normal-foreground:           @foreground;
    alternate-normal-foreground: @foreground;
    alternate-normal-background: transparent;
    selected-normal-foreground:  #{{ACCENT}};
    selected-normal-background:  rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.18);
}

window {
    font:             "FiraCode Nerd Font 11";
    background-color: rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.92);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.45);
    border-radius:    20px;
    width:            1100px;
    padding:          16px;
    children:         [ mainbox ];
}

mainbox {
    background-color: transparent;
    children:         [ inputbar, listview ];
    spacing:          14px;
}

inputbar {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.90);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.35);
    border-radius:    14px;
    padding:          10px 16px;
    children:         [ prompt, textbox-prompt-colon, entry ];
    spacing:          8px;
}

prompt {
    background-color: transparent;
    text-color:       #{{ACCENT}};
    font:             "FiraCode Nerd Font Bold 12";
    vertical-align:   0.5;
}

textbox-prompt-colon {
    background-color: transparent;
    text-color:       #{{ACCENT_ALT}};
    str:              "→";
    vertical-align:   0.5;
}

entry {
    background-color: transparent;
    text-color:       #{{FG}};
    placeholder:      "Search wallpapers…";
    placeholder-color: rgba({{FG_R}}, {{FG_G}}, {{FG_B}}, 0.35);
    vertical-align:   0.5;
}

listview {
    background-color: transparent;
    lines:            4;
    columns:          5;
    spacing:          10px;
    fixed-height:     false;
    scrollbar:        false;
    cycle:            true;
}

element {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.55);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.15);
    border-radius:    12px;
    padding:          6px;
    orientation:      vertical;
    cursor:           pointer;
}

element.selected {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.20);
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.80);
    border:           2px;
}

element-icon {
    background-color: transparent;
    size:             150px;
    border-radius:    8px;
    border:           0px;
}

element-text {
    background-color: transparent;
    text-color:       rgba({{FG_R}}, {{FG_G}}, {{FG_B}}, 0.75);
    vertical-align:   0.5;
    horizontal-align: 0.5;
    font:             "FiraCode Nerd Font 8";
    padding:          4px 2px 2px 2px;
}
