/* ── {{THEME_NAME}} — Clipboard History ──────────────────────────────────── */
/* Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead */

configuration {
    kb-custom-1: "Alt+d";
}

* {
    background-color:            transparent;
    text-color:                  #{{FG}};
    foreground:                  #{{FG}};
    background:                  rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.92);
    separatorcolor:              rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.30);
    border-color:                rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.35);
    spacing:                     0;

    normal-foreground:           @foreground;
    normal-background:           transparent;
    alternate-normal-foreground: @foreground;
    alternate-normal-background: transparent;

    selected-normal-foreground:  #{{ACCENT}};
    selected-normal-background:  rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.15);

    urgent-foreground:           #{{URGENT}};
    urgent-background:           transparent;
    alternate-urgent-foreground: #{{URGENT}};
    alternate-urgent-background: transparent;
    selected-urgent-foreground:  #{{URGENT}};
    selected-urgent-background:  rgba({{URGENT_R}}, {{URGENT_G}}, {{URGENT_B}}, 0.15);
}

window {
    font:             "FiraCode Nerd Font Mono 11";
    background-color: rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.93);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.45);
    border-radius:    16px;
    width:            640px;
    padding:          12px;
    children:         [ inputbar, listview, message ];
    spacing:          8px;
}

inputbar {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.90);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.35);
    border-radius:    12px;
    padding:          10px 14px;
    children:         [ prompt, textbox-prompt-colon, entry ];
    spacing:          6px;
}

prompt {
    background-color: transparent;
    text-color:       #{{ACCENT}};
    font:             "FiraCode Nerd Font Bold 12";
    vertical-align:   0.5;
}

textbox-prompt-colon {
    background-color: transparent;
    text-color:       #{{ACCENT_ALT}};
    str:              "→";
    vertical-align:   0.5;
}

entry {
    background-color:  transparent;
    text-color:        #{{FG}};
    placeholder:       "Search clipboard…";
    placeholder-color: rgba({{FG_R}}, {{FG_G}}, {{FG_B}}, 0.35);
    vertical-align:    0.5;
}

listview {
    background-color: transparent;
    lines:            12;
    columns:          1;
    spacing:          3px;
    fixed-height:     false;
    scrollbar:        false;
}

element {
    background-color: @normal-background;
    border:           1px;
    border-color:     transparent;
    border-radius:    10px;
    padding:          7px 12px;
    orientation:      horizontal;
}

element.selected {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.12);
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.60);
}

element-text {
    background-color: transparent;
    text-color:       inherit;
    vertical-align:   0.5;
    highlight:        bold #{{ACCENT}};
}

message {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.60);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.20);
    border-radius:    8px;
    padding:          5px 12px;
}

textbox {
    background-color: transparent;
    text-color:       rgba({{FG_R}}, {{FG_G}}, {{FG_B}}, 0.45);
    font:             "FiraCode Nerd Font 9";
    vertical-align:   0.5;
}
