/* ── {{THEME_NAME}} — Rofi Theme ─────────────────────────────────────────── */
/* Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead */

* {
    background-color:            transparent;
    text-color:                  #{{FG}};

    foreground:                  #{{FG}};
    background:                  rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.88);
    lightfg:                     #{{FG_MUTED}};
    lightbg:                     rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.92);
    separatorcolor:              rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.35);
    border-color:                rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.35);
    spacing:                     0;

    normal-foreground:           @foreground;
    normal-background:           transparent;
    alternate-normal-foreground: @foreground;
    alternate-normal-background: transparent;

    selected-normal-foreground:  #{{ACCENT}};
    selected-normal-background:  rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.15);

    urgent-foreground:           #{{URGENT}};
    urgent-background:           transparent;
    alternate-urgent-foreground: #{{URGENT}};
    alternate-urgent-background: transparent;
    selected-urgent-foreground:  #{{URGENT}};
    selected-urgent-background:  rgba({{URGENT_R}}, {{URGENT_G}}, {{URGENT_B}}, 0.15);

    active-foreground:           #{{INFO}};
    active-background:           transparent;
    alternate-active-foreground: #{{INFO}};
    alternate-active-background: transparent;
    selected-active-foreground:  #{{INFO}};
    selected-active-background:  rgba({{INFO_R}}, {{INFO_G}}, {{INFO_B}}, 0.15);
}

/* ── Window ─────────────────────────────────── */
window {
    font:             "FiraCode Nerd Font 12";
    background-color: rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.90);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.40);
    border-radius:    16px;
    width:            480px;
    padding:          12px;
    children:         [ inputbar, listview, mode-switcher ];
    spacing:          10px;
}

/* ── Input bar ──────────────────────────────── */
inputbar {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.92);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.35);
    border-radius:    12px;
    padding:          10px 14px;
    children:         [ prompt, textbox-prompt-colon, entry ];
    spacing:          6px;
}

prompt {
    background-color: transparent;
    text-color:       #{{ACCENT}};
    font:             "FiraCode Nerd Font Bold 12";
    vertical-align:   0.5;
}

textbox-prompt-colon {
    background-color: transparent;
    text-color:       #{{ACCENT_ALT}};
    str:              "→";
    vertical-align:   0.5;
}

entry {
    background-color: transparent;
    text-color:       #{{FG}};
    placeholder:      "Search…";
    vertical-align:   0.5;
}

/* ── List view ──────────────────────────────── */
listview {
    background-color: transparent;
    lines:            8;
    columns:          1;
    spacing:          4px;
    fixed-height:     false;
    scrollbar:        false;
}

/* ── Elements ───────────────────────────────── */
element {
    background-color: @normal-background;
    border:           1px;
    border-color:     transparent;
    border-radius:    10px;
    padding:          8px 12px;
    spacing:          10px;
    orientation:      horizontal;
}

element.selected {
    border-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.65);
}

element-icon {
    background-color: transparent;
    size:             22px;
    border:           0px;
}

element-text {
    background-color: transparent;
    text-color:       inherit;
    vertical-align:   0.5;
}

/* ── Mode switcher ──────────────────────────── */
mode-switcher {
    background-color: rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.80);
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.25);
    border-radius:    10px;
    padding:          6px;
    spacing:          4px;
}

button {
    background-color: transparent;
    text-color:       #{{FG_MUTED}};
    border-radius:    8px;
    padding:          4px 12px;
}

button.selected {
    background-color: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.20);
    text-color:       #{{ACCENT}};
    border:           1px;
    border-color:     rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.65);
}

/* ── Message / error ────────────────────────── */
message {
    background-color: rgba({{URGENT_R}}, {{URGENT_G}}, {{URGENT_B}}, 0.12);
    border:           1px;
    border-color:     rgba({{URGENT_R}}, {{URGENT_G}}, {{URGENT_B}}, 0.50);
    border-radius:    10px;
    padding:          8px 12px;
}

textbox {
    background-color: transparent;
    text-color:       #{{URGENT}};
}
