/* ── {{THEME_NAME}} — SwayNC Style ─────────────────────────────────────────── */
/* Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead  */

@define-color surface          rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.92);
@define-color surface_container rgba({{BG_SURFACE_R}}, {{BG_SURFACE_G}}, {{BG_SURFACE_B}}, 0.94);
@define-color surface_high     rgba({{BG_HIGH_R}}, {{BG_HIGH_G}}, {{BG_HIGH_B}}, 0.97);
@define-color surface_highest  rgba({{BG_HIGHEST_R}}, {{BG_HIGHEST_G}}, {{BG_HIGHEST_B}}, 0.98);
@define-color primary          #{{ACCENT}};
@define-color on_surface       #{{FG}};
@define-color on_surface_var   #{{FG_MUTED}};
@define-color outline          #{{OVERLAY}};
@define-color urgent           #{{URGENT}};
@define-color urgent_container rgba({{URGENT_R}}, {{URGENT_G}}, {{URGENT_B}}, 0.18);

* {
    font-family: "Noto Sans", "FiraCode Nerd Font", sans-serif;
    font-size: 13px;
    transition: all 200ms ease;
}

/* ── Control center panel ──────────────────────── */
.control-center {
    background: @surface;
    border-radius: 24px;
    border: none;
    color: @on_surface;
    padding: 10px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.5);
}

/* ── Title bar ─────────────────────────────────── */
.widget-title {
    color: @primary;
    font-size: 15px;
    font-weight: bold;
    margin: 4px 6px 8px 6px;
    padding: 0;
}

.widget-title > button {
    background: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.15);
    color: @primary;
    border: none;
    border-radius: 20px;
    padding: 5px 14px;
    font-size: 12px;
    font-weight: bold;
}

.widget-title > button:hover {
    background: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.25);
}

/* ── Do Not Disturb ────────────────────────────── */
.widget-dnd {
    margin: 0px 6px 8px 6px;
    color: @on_surface;
    font-size: 13px;
}

.widget-dnd > switch {
    border-radius: 20px;
    border: none;
    background: @surface_highest;
    color: @on_surface_var;
}

.widget-dnd > switch:checked {
    background: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.30);
    color: @primary;
}

.widget-dnd > switch slider {
    border-radius: 20px;
    min-width: 20px;
    min-height: 20px;
    background: @on_surface_var;
    border: none;
    margin: 2px;
}

.widget-dnd > switch:checked slider {
    background: @primary;
}

/* ── MPRIS media widget ─────────────────────────── */
.widget-mpris {
    background: @surface_container;
    border-radius: 18px;
    border: none;
    margin: 0px 0px 8px 0px;
    padding: 12px;
}

.widget-mpris-player {
    padding: 0;
}

.widget-mpris-title {
    font-weight: bold;
    font-size: 14px;
    color: @on_surface;
}

.widget-mpris-subtitle {
    color: @on_surface_var;
    font-size: 12px;
}

.widget-mpris > box > button,
.widget-mpris-player > box > button {
    background: transparent;
    border: none;
    border-radius: 50%;
    color: @on_surface;
    padding: 6px;
    min-width: 32px;
    min-height: 32px;
}

.widget-mpris > box > button:hover,
.widget-mpris-player > box > button:hover {
    background: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.12);
}

/* ── Notification rows ─────────────────────────── */
.notification-row {
    outline: none;
    margin: 3px 0px;
    padding: 0;
}

/* ── Notification card ─────────────────────────── */
.notification {
    background: @surface_high;
    border-radius: 18px;
    border: none;
    color: @on_surface;
    padding: 0;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.35);
}

.notification.critical {
    background: @urgent_container;
}

.notification-content {
    padding: 12px 14px;
}

/* ── Clickable notification area ───────────────── */
.notification-default-action {
    padding: 0;
    margin: 0;
    border: none;
    border-radius: 18px;
    background: transparent;
    color: @on_surface;
}

.notification-default-action:hover {
    background: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.08);
}

/* ── Action buttons ────────────────────────────── */
.notification-action {
    background: @surface_highest;
    color: @on_surface_var;
    border: none;
    border-radius: 14px;
    padding: 6px 14px;
    margin: 2px;
    font-size: 12px;
}

.notification-action:hover {
    background: rgba({{ACCENT_R}}, {{ACCENT_G}}, {{ACCENT_B}}, 0.20);
    color: @primary;
}

/* ── Close button ──────────────────────────────── */
.close-button {
    background: transparent;
    color: @on_surface_var;
    border: none;
    border-radius: 50%;
    padding: 2px;
    min-width: 20px;
    min-height: 20px;
}

.close-button:hover {
    background: rgba({{URGENT_R}}, {{URGENT_G}}, {{URGENT_B}}, 0.18);
    color: @urgent;
}

/* ── Notification summary & body ───────────────── */
.notification-summary {
    font-weight: bold;
    font-size: 13px;
    color: @on_surface;
}

.notification-body {
    font-size: 12px;
    color: @on_surface_var;
}

.notification-time {
    font-size: 11px;
    color: @outline;
}

.app-icon {
    border-radius: 50%;
}

/* ── Popup toasts (floating notifications) ─────── */
.floating-notifications {
    background: transparent;
}

.notification.popup {
    background: @surface_high;
    border-radius: 18px;
    border: none;
    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.5);
}

.notification.popup.critical {
    background: @urgent_container;
    box-shadow: 0 8px 24px rgba({{URGENT_R}}, {{URGENT_G}}, {{URGENT_B}}, 0.25);
}
