/* ── {{THEME_NAME}} — Waybar Colors ─────────────────────────────────────── */
/* Auto-generated by ~/.config/themes/apply.sh — edit the .theme file instead */
@define-color bg rgba({{BG_DARK_R}}, {{BG_DARK_G}}, {{BG_DARK_B}}, 0.7);
@define-color bg_alt rgba({{BG_MEDIUM_R}}, {{BG_MEDIUM_G}}, {{BG_MEDIUM_B}}, 0.8);
@define-color fg #{{FG}};
@define-color accent #{{ACCENT}};
@define-color accent_alt #{{ACCENT_ALT}};
@define-color urgent #{{URGENT}};
@define-color warning #{{WARNING}};
@define-color info #{{INFO}};
@define-color blur_bg rgba({{BG_BLUR_R}}, {{BG_BLUR_G}}, {{BG_BLUR_B}}, 0.5);
